# NumPy

In [1]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [6]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 3)


In [8]:
print(arr1.size)
print(arr2.size)

5
6


In [11]:
arr3=np.array([1,2,3.5,6,4.5,8])
arr3

array([1. , 2. , 3.5, 6. , 4.5, 8. ])

In [13]:
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int32
int32
float64


Random arrays

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.uniform(10,20,5)

array([13.35829166, 19.01373289, 10.61369568, 15.56300508, 15.9270709 ])

In [20]:
np.random.uniform(10,100,(2,4))

array([[27.10476459, 97.87745799, 49.16157633, 60.4454096 ],
       [75.1505913 , 78.86254139, 63.21403693, 22.92381246]])

In [24]:
arr4=np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,5)

In [23]:
arr4.shape=(5,2)
arr4

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [25]:
arr4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
np.random.randint(10,20,5)

array([10, 10, 12, 14, 19])

In [29]:
np.random.randint(10,50,(2,5)).reshape(5,2)

array([[14, 23],
       [39, 14],
       [38, 22],
       [29, 35],
       [22, 16]])

In [28]:
np.random.random(5)

array([0.6811281 , 0.43711216, 0.30042478, 0.12210484, 0.64289498])

In [30]:
np.random.random((2,5))

array([[0.41234673, 0.1240415 , 0.32871752, 0.89735512, 0.3876509 ],
       [0.64810675, 0.61268587, 0.1170977 , 0.99245711, 0.2546401 ]])

In [31]:
np.arange(1,51)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [32]:
np.arange(1,51).reshape(5,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [33]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [35]:
np.arange(1,100,10).reshape(5,2)

array([[ 1, 11],
       [21, 31],
       [41, 51],
       [61, 71],
       [81, 91]])